Differentiate between unknown command and parse error
RYGhub/royalnet pull request #14
Opened 2024-08-19 09:26 UTC by SnowyCoder

Also, minor fixes

2024-08-22 07:57 UTC, Steffo99 requested changes
brb faccio il resto dal computer

2024-08-22 07:57 UTC, Steffo99 commented on diesel.toml
> +dir = "./migrations"
```suggestion
dir = "./migrations"

```

2024-08-22 07:57 UTC, Steffo99 commented on diesel.toml
> +dir = "./migrations"
Whoops. My bad...

2024-08-22 07:57 UTC, Steffo99 commented on src/services/telegram/commands/cat.rs
> +
configura l'editor che stai usando per ruspettare `.editorconfig` pls :)

2024-08-22 09:07 UTC, SnowyCoder commented on src/services/telegram/commands/cat.rs
> +
Done, sorry!

2024-08-25 07:45 UTC, Steffo99 commented
finally i can merge this

2024-08-25 10:49 UTC, merged

2024-08-25 10:49 UTC, Steffo99 reviewed
ok